# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/vsilantiev/Documents/VACAC701new/project_1/project_1.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/vsilantiev/Documents/VACAC701new/ipcore_dir/coregen.cgc"

set ipFile "c:/Users/vsilantiev/Documents/VACAC701new/ipcore_dir/v7_pcie.xco"

set ipName "v7_pcie"

set hdlType "VHDL"

set cgPartSpec "xc7a200t-2fbg676"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/vsilantiev/Documents/VACAC701new/ipcore_dir/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

